package com.rm2pt.arkmodelproject.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;

public class InitModel {
	public static CharSequence init(String project) {
	    StringConcatenation _builder = new StringConcatenation();
	    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
	    _builder.newLine();
	    _builder.append("<arkUIModel:GUIModel xmi:version=\"2.0\" xmlns:xmi=\"http://www.omg.org/XMI\" xmlns:arkUIModel=\"http://www.example.org/arkUIModel\" description=\""+project+"\" >");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("<stylelibray name=\"stylelibray\"/>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("<rootpage>");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("<page pageTitle=\"home\" uilogic=\"//@uilogic.0\" uidesign=\"//@uidesign.0\"/>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("</rootpage>");
	    _builder.append("  ");
	    _builder.append("<animationlibray/>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("<uilogic name=\"home\">");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("<pageparameter name=\"message\" pType=\"string\" value=\"&quot;Hello,World!&quot;\" state=\"\">");
	    _builder.newLine();
	    _builder.append("      ");
	    _builder.append("<type type=\"string\"/>");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("</pageparameter>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("</uilogic>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("<uidesign name=\"home\">");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("<pageview title=\"home\">");
	    _builder.newLine();
	    _builder.append("      ");
	    _builder.append("<widgets xsi:type=\"arkUIModel:RowContainer\" id=\"行容器\" widgetType=\"Container\" root=\"//@uidesign.0/@pageview\" space=\"20\" alignItems=\"Center\" justifyContent=\"Center\">");
	    _builder.newLine();
	    _builder.append("        ");
	    _builder.append("<widget xsi:type=\"arkUIModel:ColumnContainer\" id=\"列容器\" widgetType=\"Container\" root=\"//@uidesign.0/@pageview\" justifyContent=\"Center\" alignItems=\"Center\" space=\"5\">");
	    _builder.newLine();
	    _builder.append("          ");
	    _builder.append("<widget xsi:type=\"arkUIModel:TextWidget\" id=\"文本\" widgetType=\"Widget\" root=\"//@uidesign.0/@pageview\" content=\"${message}\">");
	    _builder.newLine();
	    _builder.append("            ");
	    _builder.append("<textevent/>");
	    _builder.newLine();
	    _builder.append("            ");
	    _builder.append("<textstyle fontSize=\"50\" fontWeight=\"Bold\"/>");
	    _builder.newLine();
	    _builder.append("          ");
	    _builder.append("</widget>");
	    _builder.newLine();
	    _builder.append("          ");
	    _builder.append("<columnevent/>");
	    _builder.newLine();
	    _builder.append("          ");
	    _builder.append("<columnstyle width=\"100%\"/>");
	    _builder.newLine();
	    _builder.append("        ");
	    _builder.append("</widget>");
	    _builder.newLine();
	    _builder.append("        ");
	    _builder.append("<rowevent/>");
	    _builder.newLine();
	    _builder.append("        ");
	    _builder.append("<rowstyle height=\"100%\"/>");
	    _builder.newLine();
	    _builder.append("      ");
	    _builder.append("</widgets>");
	    _builder.newLine();
	    _builder.append("      ");
	    _builder.append("<pageevent/>");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("</pageview>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("</uidesign>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("<operationlibray name=\"operationlibray\">");
	    _builder.newLine();
	    _builder.append("    ");
	    _builder.append("<domainmodel/>");
	    _builder.newLine();
	    _builder.append("  ");
	    _builder.append("</operationlibray>");
	    _builder.newLine();
	    _builder.append("</arkUIModel:GUIModel>");
	    _builder.newLine();
	    return _builder;
	  }
}
