/**
 */
package arkuimodel.arkUIModel.provider;

import arkuimodel.arkUIModel.util.ArkUIModelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ArkUIModelItemProviderAdapterFactory extends ArkUIModelAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ArkUIModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GUIModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GUIModelItemProvider guiModelItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GUIModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGUIModelAdapter() {
		if (guiModelItemProvider == null) {
			guiModelItemProvider = new GUIModelItemProvider(this);
		}

		return guiModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.UILogic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UILogicItemProvider uiLogicItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.UILogic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUILogicAdapter() {
		if (uiLogicItemProvider == null) {
			uiLogicItemProvider = new UILogicItemProvider(this);
		}

		return uiLogicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.UIDesign} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIDesignItemProvider uiDesignItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.UIDesign}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIDesignAdapter() {
		if (uiDesignItemProvider == null) {
			uiDesignItemProvider = new UIDesignItemProvider(this);
		}

		return uiDesignItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.PageStruct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageStructItemProvider pageStructItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.PageStruct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageStructAdapter() {
		if (pageStructItemProvider == null) {
			pageStructItemProvider = new PageStructItemProvider(this);
		}

		return pageStructItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextWidgetItemProvider textWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextWidgetAdapter() {
		if (textWidgetItemProvider == null) {
			textWidgetItemProvider = new TextWidgetItemProvider(this);
		}

		return textWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ButtonWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonWidgetItemProvider buttonWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ButtonWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonWidgetAdapter() {
		if (buttonWidgetItemProvider == null) {
			buttonWidgetItemProvider = new ButtonWidgetItemProvider(this);
		}

		return buttonWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.FlexContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlexContainerItemProvider flexContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.FlexContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFlexContainerAdapter() {
		if (flexContainerItemProvider == null) {
			flexContainerItemProvider = new FlexContainerItemProvider(this);
		}

		return flexContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StyleLibray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StyleLibrayItemProvider styleLibrayItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StyleLibray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStyleLibrayAdapter() {
		if (styleLibrayItemProvider == null) {
			styleLibrayItemProvider = new StyleLibrayItemProvider(this);
		}

		return styleLibrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StyleClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StyleClassItemProvider styleClassItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StyleClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStyleClassAdapter() {
		if (styleClassItemProvider == null) {
			styleClassItemProvider = new StyleClassItemProvider(this);
		}

		return styleClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextInputWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextInputWidgetItemProvider textInputWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextInputWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextInputWidgetAdapter() {
		if (textInputWidgetItemProvider == null) {
			textInputWidgetItemProvider = new TextInputWidgetItemProvider(this);
		}

		return textInputWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListContainerItemProvider listContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListContainerAdapter() {
		if (listContainerItemProvider == null) {
			listContainerItemProvider = new ListContainerItemProvider(this);
		}

		return listContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextStyleItemProvider textStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextStyleAdapter() {
		if (textStyleItemProvider == null) {
			textStyleItemProvider = new TextStyleItemProvider(this);
		}

		return textStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextInputStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextInputStyleItemProvider textInputStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextInputStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextInputStyleAdapter() {
		if (textInputStyleItemProvider == null) {
			textInputStyleItemProvider = new TextInputStyleItemProvider(this);
		}

		return textInputStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeCSItemProvider typeCSItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeCSAdapter() {
		if (typeCSItemProvider == null) {
			typeCSItemProvider = new TypeCSItemProvider(this);
		}

		return typeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.RowContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RowContainerItemProvider rowContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.RowContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRowContainerAdapter() {
		if (rowContainerItemProvider == null) {
			rowContainerItemProvider = new RowContainerItemProvider(this);
		}

		return rowContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ColumnContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnContainerItemProvider columnContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ColumnContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnContainerAdapter() {
		if (columnContainerItemProvider == null) {
			columnContainerItemProvider = new ColumnContainerItemProvider(this);
		}

		return columnContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ButtonStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonStyleItemProvider buttonStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ButtonStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonStyleAdapter() {
		if (buttonStyleItemProvider == null) {
			buttonStyleItemProvider = new ButtonStyleItemProvider(this);
		}

		return buttonStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.FlexStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlexStyleItemProvider flexStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.FlexStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFlexStyleAdapter() {
		if (flexStyleItemProvider == null) {
			flexStyleItemProvider = new FlexStyleItemProvider(this);
		}

		return flexStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.RowStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RowStyleItemProvider rowStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.RowStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRowStyleAdapter() {
		if (rowStyleItemProvider == null) {
			rowStyleItemProvider = new RowStyleItemProvider(this);
		}

		return rowStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ColumnStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnStyleItemProvider columnStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ColumnStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnStyleAdapter() {
		if (columnStyleItemProvider == null) {
			columnStyleItemProvider = new ColumnStyleItemProvider(this);
		}

		return columnStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListStyleItemProvider listStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListStyleAdapter() {
		if (listStyleItemProvider == null) {
			listStyleItemProvider = new ListStyleItemProvider(this);
		}

		return listStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListItemStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListItemStyleItemProvider listItemStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListItemStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListItemStyleAdapter() {
		if (listItemStyleItemProvider == null) {
			listItemStyleItemProvider = new ListItemStyleItemProvider(this);
		}

		return listItemStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListItemContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListItemContainerItemProvider listItemContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListItemContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListItemContainerAdapter() {
		if (listItemContainerItemProvider == null) {
			listItemContainerItemProvider = new ListItemContainerItemProvider(this);
		}

		return listItemContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageWidgetItemProvider imageWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageWidgetAdapter() {
		if (imageWidgetItemProvider == null) {
			imageWidgetItemProvider = new ImageWidgetItemProvider(this);
		}

		return imageWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageStyleItemProvider imageStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageStyleAdapter() {
		if (imageStyleItemProvider == null) {
			imageStyleItemProvider = new ImageStyleItemProvider(this);
		}

		return imageStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TriggerEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerEventItemProvider triggerEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TriggerEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerEventAdapter() {
		if (triggerEventItemProvider == null) {
			triggerEventItemProvider = new TriggerEventItemProvider(this);
		}

		return triggerEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Event} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventItemProvider eventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Event}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventAdapter() {
		if (eventItemProvider == null) {
			eventItemProvider = new EventItemProvider(this);
		}

		return eventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.PageEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageEventItemProvider pageEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.PageEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageEventAdapter() {
		if (pageEventItemProvider == null) {
			pageEventItemProvider = new PageEventItemProvider(this);
		}

		return pageEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ColumnEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnEventItemProvider columnEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ColumnEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnEventAdapter() {
		if (columnEventItemProvider == null) {
			columnEventItemProvider = new ColumnEventItemProvider(this);
		}

		return columnEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.RowEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RowEventItemProvider rowEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.RowEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRowEventAdapter() {
		if (rowEventItemProvider == null) {
			rowEventItemProvider = new RowEventItemProvider(this);
		}

		return rowEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.FlexEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlexEventItemProvider flexEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.FlexEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFlexEventAdapter() {
		if (flexEventItemProvider == null) {
			flexEventItemProvider = new FlexEventItemProvider(this);
		}

		return flexEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageEventItemProvider imageEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageEventAdapter() {
		if (imageEventItemProvider == null) {
			imageEventItemProvider = new ImageEventItemProvider(this);
		}

		return imageEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextEventItemProvider textEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextEventAdapter() {
		if (textEventItemProvider == null) {
			textEventItemProvider = new TextEventItemProvider(this);
		}

		return textEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ButtonEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonEventItemProvider buttonEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ButtonEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonEventAdapter() {
		if (buttonEventItemProvider == null) {
			buttonEventItemProvider = new ButtonEventItemProvider(this);
		}

		return buttonEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextInputEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextInputEventItemProvider textInputEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextInputEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextInputEventAdapter() {
		if (textInputEventItemProvider == null) {
			textInputEventItemProvider = new TextInputEventItemProvider(this);
		}

		return textInputEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListEventItemProvider listEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListEventAdapter() {
		if (listEventItemProvider == null) {
			listEventItemProvider = new ListEventItemProvider(this);
		}

		return listEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ListItemEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListItemEventItemProvider listItemEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ListItemEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListItemEventAdapter() {
		if (listItemEventItemProvider == null) {
			listItemEventItemProvider = new ListItemEventItemProvider(this);
		}

		return listItemEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.LoopOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopOpItemProvider loopOpItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.LoopOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopOpAdapter() {
		if (loopOpItemProvider == null) {
			loopOpItemProvider = new LoopOpItemProvider(this);
		}

		return loopOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CaseOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CaseOpItemProvider caseOpItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CaseOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCaseOpAdapter() {
		if (caseOpItemProvider == null) {
			caseOpItemProvider = new CaseOpItemProvider(this);
		}

		return caseOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.HttpOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HttpOperationItemProvider httpOperationItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.HttpOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHttpOperationAdapter() {
		if (httpOperationItemProvider == null) {
			httpOperationItemProvider = new HttpOperationItemProvider(this);
		}

		return httpOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GetParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetParameterItemProvider getParameterItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GetParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetParameterAdapter() {
		if (getParameterItemProvider == null) {
			getParameterItemProvider = new GetParameterItemProvider(this);
		}

		return getParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SetParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetParameterItemProvider setParameterItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SetParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetParameterAdapter() {
		if (setParameterItemProvider == null) {
			setParameterItemProvider = new SetParameterItemProvider(this);
		}

		return setParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.AnimationClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnimationClassItemProvider animationClassItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.AnimationClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnimationClassAdapter() {
		if (animationClassItemProvider == null) {
			animationClassItemProvider = new AnimationClassItemProvider(this);
		}

		return animationClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageAnimator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageAnimatorItemProvider imageAnimatorItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageAnimator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAnimatorAdapter() {
		if (imageAnimatorItemProvider == null) {
			imageAnimatorItemProvider = new ImageAnimatorItemProvider(this);
		}

		return imageAnimatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImagesItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImagesItemItemProvider imagesItemItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImagesItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImagesItemAdapter() {
		if (imagesItemItemProvider == null) {
			imagesItemItemProvider = new ImagesItemItemProvider(this);
		}

		return imagesItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageAnimatorStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageAnimatorStyleItemProvider imageAnimatorStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageAnimatorStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAnimatorStyleAdapter() {
		if (imageAnimatorStyleItemProvider == null) {
			imageAnimatorStyleItemProvider = new ImageAnimatorStyleItemProvider(this);
		}

		return imageAnimatorStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ImageAnimatorEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageAnimatorEventItemProvider imageAnimatorEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ImageAnimatorEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAnimatorEventAdapter() {
		if (imageAnimatorEventItemProvider == null) {
			imageAnimatorEventItemProvider = new ImageAnimatorEventItemProvider(this);
		}

		return imageAnimatorEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.RouteSkip} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouteSkipItemProvider routeSkipItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.RouteSkip}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRouteSkipAdapter() {
		if (routeSkipItemProvider == null) {
			routeSkipItemProvider = new RouteSkipItemProvider(this);
		}

		return routeSkipItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GetRouteValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetRouteValueItemProvider getRouteValueItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GetRouteValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetRouteValueAdapter() {
		if (getRouteValueItemProvider == null) {
			getRouteValueItemProvider = new GetRouteValueItemProvider(this);
		}

		return getRouteValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SeqOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeqOpItemProvider seqOpItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SeqOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSeqOpAdapter() {
		if (seqOpItemProvider == null) {
			seqOpItemProvider = new SeqOpItemProvider(this);
		}

		return seqOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.UIStruct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIStructItemProvider uiStructItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.UIStruct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIStructAdapter() {
		if (uiStructItemProvider == null) {
			uiStructItemProvider = new UIStructItemProvider(this);
		}

		return uiStructItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.AnimationLibray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnimationLibrayItemProvider animationLibrayItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.AnimationLibray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnimationLibrayAdapter() {
		if (animationLibrayItemProvider == null) {
			animationLibrayItemProvider = new AnimationLibrayItemProvider(this);
		}

		return animationLibrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.EntityAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityAttributeItemProvider entityAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.EntityAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAttributeAdapter() {
		if (entityAttributeItemProvider == null) {
			entityAttributeItemProvider = new EntityAttributeItemProvider(this);
		}

		return entityAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Array} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayItemProvider arrayItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Array}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAdapter() {
		if (arrayItemProvider == null) {
			arrayItemProvider = new ArrayItemProvider(this);
		}

		return arrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.NavigationContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationContainerItemProvider navigationContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.NavigationContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationContainerAdapter() {
		if (navigationContainerItemProvider == null) {
			navigationContainerItemProvider = new NavigationContainerItemProvider(this);
		}

		return navigationContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.NavigationStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationStyleItemProvider navigationStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.NavigationStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationStyleAdapter() {
		if (navigationStyleItemProvider == null) {
			navigationStyleItemProvider = new NavigationStyleItemProvider(this);
		}

		return navigationStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.NavigationEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationEventItemProvider navigationEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.NavigationEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationEventAdapter() {
		if (navigationEventItemProvider == null) {
			navigationEventItemProvider = new NavigationEventItemProvider(this);
		}

		return navigationEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ContainerItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerItemItemProvider containerItemItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ContainerItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerItemAdapter() {
		if (containerItemItemProvider == null) {
			containerItemItemProvider = new ContainerItemItemProvider(this);
		}

		return containerItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ContainerItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerItemsItemProvider containerItemsItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ContainerItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerItemsAdapter() {
		if (containerItemsItemProvider == null) {
			containerItemsItemProvider = new ContainerItemsItemProvider(this);
		}

		return containerItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StartOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StartOpItemProvider startOpItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StartOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStartOpAdapter() {
		if (startOpItemProvider == null) {
			startOpItemProvider = new StartOpItemProvider(this);
		}

		return startOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.EndOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndOpItemProvider endOpItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.EndOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndOpAdapter() {
		if (endOpItemProvider == null) {
			endOpItemProvider = new EndOpItemProvider(this);
		}

		return endOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.WorkFlow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkFlowItemProvider workFlowItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.WorkFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkFlowAdapter() {
		if (workFlowItemProvider == null) {
			workFlowItemProvider = new WorkFlowItemProvider(this);
		}

		return workFlowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CheckEqual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CheckEqualItemProvider checkEqualItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CheckEqual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCheckEqualAdapter() {
		if (checkEqualItemProvider == null) {
			checkEqualItemProvider = new CheckEqualItemProvider(this);
		}

		return checkEqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.FlowLine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlowLineItemProvider flowLineItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.FlowLine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFlowLineAdapter() {
		if (flowLineItemProvider == null) {
			flowLineItemProvider = new FlowLineItemProvider(this);
		}

		return flowLineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Expression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionItemProvider expressionItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionAdapter() {
		if (expressionItemProvider == null) {
			expressionItemProvider = new ExpressionItemProvider(this);
		}

		return expressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ForEach} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForEachItemProvider forEachItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ForEach}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForEachAdapter() {
		if (forEachItemProvider == null) {
			forEachItemProvider = new ForEachItemProvider(this);
		}

		return forEachItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.IF} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IFItemProvider ifItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.IF}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIFAdapter() {
		if (ifItemProvider == null) {
			ifItemProvider = new IFItemProvider(this);
		}

		return ifItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CallFun} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallFunItemProvider callFunItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CallFun}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallFunAdapter() {
		if (callFunItemProvider == null) {
			callFunItemProvider = new CallFunItemProvider(this);
		}

		return callFunItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SwiperWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwiperWidgetItemProvider swiperWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SwiperWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwiperWidgetAdapter() {
		if (swiperWidgetItemProvider == null) {
			swiperWidgetItemProvider = new SwiperWidgetItemProvider(this);
		}

		return swiperWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SwiperStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwiperStyleItemProvider swiperStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SwiperStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwiperStyleAdapter() {
		if (swiperStyleItemProvider == null) {
			swiperStyleItemProvider = new SwiperStyleItemProvider(this);
		}

		return swiperStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SwiperEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwiperEventItemProvider swiperEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SwiperEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwiperEventAdapter() {
		if (swiperEventItemProvider == null) {
			swiperEventItemProvider = new SwiperEventItemProvider(this);
		}

		return swiperEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.OperationLibray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationLibrayItemProvider operationLibrayItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.OperationLibray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationLibrayAdapter() {
		if (operationLibrayItemProvider == null) {
			operationLibrayItemProvider = new OperationLibrayItemProvider(this);
		}

		return operationLibrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.PageRefrence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageRefrenceItemProvider pageRefrenceItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.PageRefrence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageRefrenceAdapter() {
		if (pageRefrenceItemProvider == null) {
			pageRefrenceItemProvider = new PageRefrenceItemProvider(this);
		}

		return pageRefrenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabsContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabsContainerItemProvider tabsContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabsContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabsContainerAdapter() {
		if (tabsContainerItemProvider == null) {
			tabsContainerItemProvider = new TabsContainerItemProvider(this);
		}

		return tabsContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabContentItemProvider tabContentItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabContentAdapter() {
		if (tabContentItemProvider == null) {
			tabContentItemProvider = new TabContentItemProvider(this);
		}

		return tabContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabsStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabsStyleItemProvider tabsStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabsStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabsStyleAdapter() {
		if (tabsStyleItemProvider == null) {
			tabsStyleItemProvider = new TabsStyleItemProvider(this);
		}

		return tabsStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabItemItemProvider tabItemItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabItemAdapter() {
		if (tabItemItemProvider == null) {
			tabItemItemProvider = new TabItemItemProvider(this);
		}

		return tabItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabsEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabsEventItemProvider tabsEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabsEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabsEventAdapter() {
		if (tabsEventItemProvider == null) {
			tabsEventItemProvider = new TabsEventItemProvider(this);
		}

		return tabsEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StackContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StackContainerItemProvider stackContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StackContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStackContainerAdapter() {
		if (stackContainerItemProvider == null) {
			stackContainerItemProvider = new StackContainerItemProvider(this);
		}

		return stackContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StackEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StackEventItemProvider stackEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StackEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStackEventAdapter() {
		if (stackEventItemProvider == null) {
			stackEventItemProvider = new StackEventItemProvider(this);
		}

		return stackEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.StackStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StackStyleItemProvider stackStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.StackStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStackStyleAdapter() {
		if (stackStyleItemProvider == null) {
			stackStyleItemProvider = new StackStyleItemProvider(this);
		}

		return stackStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ScrollContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScrollContainerItemProvider scrollContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ScrollContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScrollContainerAdapter() {
		if (scrollContainerItemProvider == null) {
			scrollContainerItemProvider = new ScrollContainerItemProvider(this);
		}

		return scrollContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ScrollEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScrollEventItemProvider scrollEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ScrollEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScrollEventAdapter() {
		if (scrollEventItemProvider == null) {
			scrollEventItemProvider = new ScrollEventItemProvider(this);
		}

		return scrollEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ScrollStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScrollStyleItemProvider scrollStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ScrollStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScrollStyleAdapter() {
		if (scrollStyleItemProvider == null) {
			scrollStyleItemProvider = new ScrollStyleItemProvider(this);
		}

		return scrollStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.Scroller} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScrollerItemProvider scrollerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.Scroller}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScrollerAdapter() {
		if (scrollerItemProvider == null) {
			scrollerItemProvider = new ScrollerItemProvider(this);
		}

		return scrollerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ToggleWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToggleWidgetItemProvider toggleWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ToggleWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToggleWidgetAdapter() {
		if (toggleWidgetItemProvider == null) {
			toggleWidgetItemProvider = new ToggleWidgetItemProvider(this);
		}

		return toggleWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ToggleEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToggleEventItemProvider toggleEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ToggleEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToggleEventAdapter() {
		if (toggleEventItemProvider == null) {
			toggleEventItemProvider = new ToggleEventItemProvider(this);
		}

		return toggleEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ToggleStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToggleStyleItemProvider toggleStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ToggleStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToggleStyleAdapter() {
		if (toggleStyleItemProvider == null) {
			toggleStyleItemProvider = new ToggleStyleItemProvider(this);
		}

		return toggleStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TimePickerWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimePickerWidgetItemProvider timePickerWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TimePickerWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimePickerWidgetAdapter() {
		if (timePickerWidgetItemProvider == null) {
			timePickerWidgetItemProvider = new TimePickerWidgetItemProvider(this);
		}

		return timePickerWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TimePickerEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimePickerEventItemProvider timePickerEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TimePickerEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimePickerEventAdapter() {
		if (timePickerEventItemProvider == null) {
			timePickerEventItemProvider = new TimePickerEventItemProvider(this);
		}

		return timePickerEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TimePickerStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimePickerStyleItemProvider timePickerStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TimePickerStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimePickerStyleAdapter() {
		if (timePickerStyleItemProvider == null) {
			timePickerStyleItemProvider = new TimePickerStyleItemProvider(this);
		}

		return timePickerStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DatePickerWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatePickerWidgetItemProvider datePickerWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DatePickerWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatePickerWidgetAdapter() {
		if (datePickerWidgetItemProvider == null) {
			datePickerWidgetItemProvider = new DatePickerWidgetItemProvider(this);
		}

		return datePickerWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DatePickerEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatePickerEventItemProvider datePickerEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DatePickerEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatePickerEventAdapter() {
		if (datePickerEventItemProvider == null) {
			datePickerEventItemProvider = new DatePickerEventItemProvider(this);
		}

		return datePickerEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DatePickerStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatePickerStyleItemProvider datePickerStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DatePickerStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatePickerStyleAdapter() {
		if (datePickerStyleItemProvider == null) {
			datePickerStyleItemProvider = new DatePickerStyleItemProvider(this);
		}

		return datePickerStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextPickerWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextPickerWidgetItemProvider textPickerWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextPickerWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextPickerWidgetAdapter() {
		if (textPickerWidgetItemProvider == null) {
			textPickerWidgetItemProvider = new TextPickerWidgetItemProvider(this);
		}

		return textPickerWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextPickerEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextPickerEventItemProvider textPickerEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextPickerEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextPickerEventAdapter() {
		if (textPickerEventItemProvider == null) {
			textPickerEventItemProvider = new TextPickerEventItemProvider(this);
		}

		return textPickerEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TextPickerStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextPickerStyleItemProvider textPickerStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TextPickerStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextPickerStyleAdapter() {
		if (textPickerStyleItemProvider == null) {
			textPickerStyleItemProvider = new TextPickerStyleItemProvider(this);
		}

		return textPickerStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DividerWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DividerWidgetItemProvider dividerWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DividerWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDividerWidgetAdapter() {
		if (dividerWidgetItemProvider == null) {
			dividerWidgetItemProvider = new DividerWidgetItemProvider(this);
		}

		return dividerWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DividerStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DividerStyleItemProvider dividerStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DividerStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDividerStyleAdapter() {
		if (dividerStyleItemProvider == null) {
			dividerStyleItemProvider = new DividerStyleItemProvider(this);
		}

		return dividerStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CustomDialogContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomDialogContainerItemProvider customDialogContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CustomDialogContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomDialogContainerAdapter() {
		if (customDialogContainerItemProvider == null) {
			customDialogContainerItemProvider = new CustomDialogContainerItemProvider(this);
		}

		return customDialogContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CustomDialogStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomDialogStyleItemProvider customDialogStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CustomDialogStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomDialogStyleAdapter() {
		if (customDialogStyleItemProvider == null) {
			customDialogStyleItemProvider = new CustomDialogStyleItemProvider(this);
		}

		return customDialogStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CustomDialogEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomDialogEventItemProvider customDialogEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CustomDialogEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomDialogEventAdapter() {
		if (customDialogEventItemProvider == null) {
			customDialogEventItemProvider = new CustomDialogEventItemProvider(this);
		}

		return customDialogEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.OpenDialog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpenDialogItemProvider openDialogItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.OpenDialog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpenDialogAdapter() {
		if (openDialogItemProvider == null) {
			openDialogItemProvider = new OpenDialogItemProvider(this);
		}

		return openDialogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.CloseDialog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CloseDialogItemProvider closeDialogItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.CloseDialog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCloseDialogAdapter() {
		if (closeDialogItemProvider == null) {
			closeDialogItemProvider = new CloseDialogItemProvider(this);
		}

		return closeDialogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DataPreferences} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPreferencesItemProvider dataPreferencesItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DataPreferences}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPreferencesAdapter() {
		if (dataPreferencesItemProvider == null) {
			dataPreferencesItemProvider = new DataPreferencesItemProvider(this);
		}

		return dataPreferencesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TerminateSelf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TerminateSelfItemProvider terminateSelfItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TerminateSelf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTerminateSelfAdapter() {
		if (terminateSelfItemProvider == null) {
			terminateSelfItemProvider = new TerminateSelfItemProvider(this);
		}

		return terminateSelfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SetTimeOut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetTimeOutItemProvider setTimeOutItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SetTimeOut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetTimeOutAdapter() {
		if (setTimeOutItemProvider == null) {
			setTimeOutItemProvider = new SetTimeOutItemProvider(this);
		}

		return setTimeOutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ClearTimeOut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClearTimeOutItemProvider clearTimeOutItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ClearTimeOut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClearTimeOutAdapter() {
		if (clearTimeOutItemProvider == null) {
			clearTimeOutItemProvider = new ClearTimeOutItemProvider(this);
		}

		return clearTimeOutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ShowToastOptions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShowToastOptionsItemProvider showToastOptionsItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ShowToastOptions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShowToastOptionsAdapter() {
		if (showToastOptionsItemProvider == null) {
			showToastOptionsItemProvider = new ShowToastOptionsItemProvider(this);
		}

		return showToastOptionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.DomainModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainModelItemProvider domainModelItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.DomainModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainModelAdapter() {
		if (domainModelItemProvider == null) {
			domainModelItemProvider = new DomainModelItemProvider(this);
		}

		return domainModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.EntityRefrence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityRefrenceItemProvider entityRefrenceItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.EntityRefrence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityRefrenceAdapter() {
		if (entityRefrenceItemProvider == null) {
			entityRefrenceItemProvider = new EntityRefrenceItemProvider(this);
		}

		return entityRefrenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridContainerItemProvider gridContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridContainerAdapter() {
		if (gridContainerItemProvider == null) {
			gridContainerItemProvider = new GridContainerItemProvider(this);
		}

		return gridContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridEventItemProvider gridEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridEventAdapter() {
		if (gridEventItemProvider == null) {
			gridEventItemProvider = new GridEventItemProvider(this);
		}

		return gridEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridStyleItemProvider gridStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridStyleAdapter() {
		if (gridStyleItemProvider == null) {
			gridStyleItemProvider = new GridStyleItemProvider(this);
		}

		return gridStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ChangeIndex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeIndexItemProvider changeIndexItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ChangeIndex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeIndexAdapter() {
		if (changeIndexItemProvider == null) {
			changeIndexItemProvider = new ChangeIndexItemProvider(this);
		}

		return changeIndexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.TabContentStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabContentStyleItemProvider tabContentStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.TabContentStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabContentStyleAdapter() {
		if (tabContentStyleItemProvider == null) {
			tabContentStyleItemProvider = new TabContentStyleItemProvider(this);
		}

		return tabContentStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridItemContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridItemContainerItemProvider gridItemContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridItemContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridItemContainerAdapter() {
		if (gridItemContainerItemProvider == null) {
			gridItemContainerItemProvider = new GridItemContainerItemProvider(this);
		}

		return gridItemContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SearchWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchWidgetItemProvider searchWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SearchWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchWidgetAdapter() {
		if (searchWidgetItemProvider == null) {
			searchWidgetItemProvider = new SearchWidgetItemProvider(this);
		}

		return searchWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SearchEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchEventItemProvider searchEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SearchEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchEventAdapter() {
		if (searchEventItemProvider == null) {
			searchEventItemProvider = new SearchEventItemProvider(this);
		}

		return searchEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.SearchStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchStyleItemProvider searchStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.SearchStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchStyleAdapter() {
		if (searchStyleItemProvider == null) {
			searchStyleItemProvider = new SearchStyleItemProvider(this);
		}

		return searchStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.BlankWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlankWidgetItemProvider blankWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.BlankWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlankWidgetAdapter() {
		if (blankWidgetItemProvider == null) {
			blankWidgetItemProvider = new BlankWidgetItemProvider(this);
		}

		return blankWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.BlankStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlankStyleItemProvider blankStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.BlankStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlankStyleAdapter() {
		if (blankStyleItemProvider == null) {
			blankStyleItemProvider = new BlankStyleItemProvider(this);
		}

		return blankStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ProgressWidget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProgressWidgetItemProvider progressWidgetItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ProgressWidget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProgressWidgetAdapter() {
		if (progressWidgetItemProvider == null) {
			progressWidgetItemProvider = new ProgressWidgetItemProvider(this);
		}

		return progressWidgetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ProgressStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProgressStyleItemProvider progressStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ProgressStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProgressStyleAdapter() {
		if (progressStyleItemProvider == null) {
			progressStyleItemProvider = new ProgressStyleItemProvider(this);
		}

		return progressStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.ProgressEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProgressEventItemProvider progressEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.ProgressEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProgressEventAdapter() {
		if (progressEventItemProvider == null) {
			progressEventItemProvider = new ProgressEventItemProvider(this);
		}

		return progressEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.LineContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineContainerItemProvider lineContainerItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.LineContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineContainerAdapter() {
		if (lineContainerItemProvider == null) {
			lineContainerItemProvider = new LineContainerItemProvider(this);
		}

		return lineContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.LineEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineEventItemProvider lineEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.LineEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineEventAdapter() {
		if (lineEventItemProvider == null) {
			lineEventItemProvider = new LineEventItemProvider(this);
		}

		return lineEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.LineStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineStyleItemProvider lineStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.LineStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineStyleAdapter() {
		if (lineStyleItemProvider == null) {
			lineStyleItemProvider = new LineStyleItemProvider(this);
		}

		return lineStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.WorkOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkOperationItemProvider workOperationItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.WorkOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkOperationAdapter() {
		if (workOperationItemProvider == null) {
			workOperationItemProvider = new WorkOperationItemProvider(this);
		}

		return workOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridItemStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridItemStyleItemProvider gridItemStyleItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridItemStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridItemStyleAdapter() {
		if (gridItemStyleItemProvider == null) {
			gridItemStyleItemProvider = new GridItemStyleItemProvider(this);
		}

		return gridItemStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link arkuimodel.arkUIModel.GridItemEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridItemEventItemProvider gridItemEventItemProvider;

	/**
	 * This creates an adapter for a {@link arkuimodel.arkUIModel.GridItemEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridItemEventAdapter() {
		if (gridItemEventItemProvider == null) {
			gridItemEventItemProvider = new GridItemEventItemProvider(this);
		}

		return gridItemEventItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (guiModelItemProvider != null)
			guiModelItemProvider.dispose();
		if (pageItemProvider != null)
			pageItemProvider.dispose();
		if (uiLogicItemProvider != null)
			uiLogicItemProvider.dispose();
		if (uiDesignItemProvider != null)
			uiDesignItemProvider.dispose();
		if (pageStructItemProvider != null)
			pageStructItemProvider.dispose();
		if (textWidgetItemProvider != null)
			textWidgetItemProvider.dispose();
		if (buttonWidgetItemProvider != null)
			buttonWidgetItemProvider.dispose();
		if (flexContainerItemProvider != null)
			flexContainerItemProvider.dispose();
		if (styleLibrayItemProvider != null)
			styleLibrayItemProvider.dispose();
		if (styleClassItemProvider != null)
			styleClassItemProvider.dispose();
		if (textInputWidgetItemProvider != null)
			textInputWidgetItemProvider.dispose();
		if (listContainerItemProvider != null)
			listContainerItemProvider.dispose();
		if (textStyleItemProvider != null)
			textStyleItemProvider.dispose();
		if (textInputStyleItemProvider != null)
			textInputStyleItemProvider.dispose();
		if (parameterItemProvider != null)
			parameterItemProvider.dispose();
		if (typeCSItemProvider != null)
			typeCSItemProvider.dispose();
		if (rowContainerItemProvider != null)
			rowContainerItemProvider.dispose();
		if (columnContainerItemProvider != null)
			columnContainerItemProvider.dispose();
		if (buttonStyleItemProvider != null)
			buttonStyleItemProvider.dispose();
		if (flexStyleItemProvider != null)
			flexStyleItemProvider.dispose();
		if (rowStyleItemProvider != null)
			rowStyleItemProvider.dispose();
		if (columnStyleItemProvider != null)
			columnStyleItemProvider.dispose();
		if (listStyleItemProvider != null)
			listStyleItemProvider.dispose();
		if (listItemStyleItemProvider != null)
			listItemStyleItemProvider.dispose();
		if (listItemContainerItemProvider != null)
			listItemContainerItemProvider.dispose();
		if (imageWidgetItemProvider != null)
			imageWidgetItemProvider.dispose();
		if (imageStyleItemProvider != null)
			imageStyleItemProvider.dispose();
		if (triggerEventItemProvider != null)
			triggerEventItemProvider.dispose();
		if (eventItemProvider != null)
			eventItemProvider.dispose();
		if (pageEventItemProvider != null)
			pageEventItemProvider.dispose();
		if (columnEventItemProvider != null)
			columnEventItemProvider.dispose();
		if (rowEventItemProvider != null)
			rowEventItemProvider.dispose();
		if (flexEventItemProvider != null)
			flexEventItemProvider.dispose();
		if (imageEventItemProvider != null)
			imageEventItemProvider.dispose();
		if (textEventItemProvider != null)
			textEventItemProvider.dispose();
		if (buttonEventItemProvider != null)
			buttonEventItemProvider.dispose();
		if (textInputEventItemProvider != null)
			textInputEventItemProvider.dispose();
		if (listEventItemProvider != null)
			listEventItemProvider.dispose();
		if (listItemEventItemProvider != null)
			listItemEventItemProvider.dispose();
		if (loopOpItemProvider != null)
			loopOpItemProvider.dispose();
		if (caseOpItemProvider != null)
			caseOpItemProvider.dispose();
		if (httpOperationItemProvider != null)
			httpOperationItemProvider.dispose();
		if (getParameterItemProvider != null)
			getParameterItemProvider.dispose();
		if (setParameterItemProvider != null)
			setParameterItemProvider.dispose();
		if (animationClassItemProvider != null)
			animationClassItemProvider.dispose();
		if (imageAnimatorItemProvider != null)
			imageAnimatorItemProvider.dispose();
		if (imagesItemItemProvider != null)
			imagesItemItemProvider.dispose();
		if (imageAnimatorStyleItemProvider != null)
			imageAnimatorStyleItemProvider.dispose();
		if (imageAnimatorEventItemProvider != null)
			imageAnimatorEventItemProvider.dispose();
		if (routeSkipItemProvider != null)
			routeSkipItemProvider.dispose();
		if (getRouteValueItemProvider != null)
			getRouteValueItemProvider.dispose();
		if (seqOpItemProvider != null)
			seqOpItemProvider.dispose();
		if (uiStructItemProvider != null)
			uiStructItemProvider.dispose();
		if (animationLibrayItemProvider != null)
			animationLibrayItemProvider.dispose();
		if (entityItemProvider != null)
			entityItemProvider.dispose();
		if (entityAttributeItemProvider != null)
			entityAttributeItemProvider.dispose();
		if (arrayItemProvider != null)
			arrayItemProvider.dispose();
		if (navigationContainerItemProvider != null)
			navigationContainerItemProvider.dispose();
		if (navigationStyleItemProvider != null)
			navigationStyleItemProvider.dispose();
		if (navigationEventItemProvider != null)
			navigationEventItemProvider.dispose();
		if (containerItemItemProvider != null)
			containerItemItemProvider.dispose();
		if (containerItemsItemProvider != null)
			containerItemsItemProvider.dispose();
		if (startOpItemProvider != null)
			startOpItemProvider.dispose();
		if (endOpItemProvider != null)
			endOpItemProvider.dispose();
		if (workFlowItemProvider != null)
			workFlowItemProvider.dispose();
		if (checkEqualItemProvider != null)
			checkEqualItemProvider.dispose();
		if (flowLineItemProvider != null)
			flowLineItemProvider.dispose();
		if (expressionItemProvider != null)
			expressionItemProvider.dispose();
		if (functionItemProvider != null)
			functionItemProvider.dispose();
		if (forEachItemProvider != null)
			forEachItemProvider.dispose();
		if (ifItemProvider != null)
			ifItemProvider.dispose();
		if (callFunItemProvider != null)
			callFunItemProvider.dispose();
		if (swiperWidgetItemProvider != null)
			swiperWidgetItemProvider.dispose();
		if (swiperStyleItemProvider != null)
			swiperStyleItemProvider.dispose();
		if (swiperEventItemProvider != null)
			swiperEventItemProvider.dispose();
		if (operationLibrayItemProvider != null)
			operationLibrayItemProvider.dispose();
		if (pageRefrenceItemProvider != null)
			pageRefrenceItemProvider.dispose();
		if (tabsContainerItemProvider != null)
			tabsContainerItemProvider.dispose();
		if (tabContentItemProvider != null)
			tabContentItemProvider.dispose();
		if (tabsStyleItemProvider != null)
			tabsStyleItemProvider.dispose();
		if (tabItemItemProvider != null)
			tabItemItemProvider.dispose();
		if (tabsEventItemProvider != null)
			tabsEventItemProvider.dispose();
		if (stackContainerItemProvider != null)
			stackContainerItemProvider.dispose();
		if (stackEventItemProvider != null)
			stackEventItemProvider.dispose();
		if (stackStyleItemProvider != null)
			stackStyleItemProvider.dispose();
		if (scrollContainerItemProvider != null)
			scrollContainerItemProvider.dispose();
		if (scrollEventItemProvider != null)
			scrollEventItemProvider.dispose();
		if (scrollStyleItemProvider != null)
			scrollStyleItemProvider.dispose();
		if (scrollerItemProvider != null)
			scrollerItemProvider.dispose();
		if (toggleWidgetItemProvider != null)
			toggleWidgetItemProvider.dispose();
		if (toggleEventItemProvider != null)
			toggleEventItemProvider.dispose();
		if (toggleStyleItemProvider != null)
			toggleStyleItemProvider.dispose();
		if (timePickerWidgetItemProvider != null)
			timePickerWidgetItemProvider.dispose();
		if (timePickerEventItemProvider != null)
			timePickerEventItemProvider.dispose();
		if (timePickerStyleItemProvider != null)
			timePickerStyleItemProvider.dispose();
		if (datePickerWidgetItemProvider != null)
			datePickerWidgetItemProvider.dispose();
		if (datePickerEventItemProvider != null)
			datePickerEventItemProvider.dispose();
		if (datePickerStyleItemProvider != null)
			datePickerStyleItemProvider.dispose();
		if (textPickerWidgetItemProvider != null)
			textPickerWidgetItemProvider.dispose();
		if (textPickerEventItemProvider != null)
			textPickerEventItemProvider.dispose();
		if (textPickerStyleItemProvider != null)
			textPickerStyleItemProvider.dispose();
		if (dividerWidgetItemProvider != null)
			dividerWidgetItemProvider.dispose();
		if (dividerStyleItemProvider != null)
			dividerStyleItemProvider.dispose();
		if (customDialogContainerItemProvider != null)
			customDialogContainerItemProvider.dispose();
		if (customDialogStyleItemProvider != null)
			customDialogStyleItemProvider.dispose();
		if (customDialogEventItemProvider != null)
			customDialogEventItemProvider.dispose();
		if (openDialogItemProvider != null)
			openDialogItemProvider.dispose();
		if (closeDialogItemProvider != null)
			closeDialogItemProvider.dispose();
		if (dataPreferencesItemProvider != null)
			dataPreferencesItemProvider.dispose();
		if (terminateSelfItemProvider != null)
			terminateSelfItemProvider.dispose();
		if (setTimeOutItemProvider != null)
			setTimeOutItemProvider.dispose();
		if (clearTimeOutItemProvider != null)
			clearTimeOutItemProvider.dispose();
		if (showToastOptionsItemProvider != null)
			showToastOptionsItemProvider.dispose();
		if (domainModelItemProvider != null)
			domainModelItemProvider.dispose();
		if (entityRefrenceItemProvider != null)
			entityRefrenceItemProvider.dispose();
		if (gridContainerItemProvider != null)
			gridContainerItemProvider.dispose();
		if (gridEventItemProvider != null)
			gridEventItemProvider.dispose();
		if (gridStyleItemProvider != null)
			gridStyleItemProvider.dispose();
		if (changeIndexItemProvider != null)
			changeIndexItemProvider.dispose();
		if (tabContentStyleItemProvider != null)
			tabContentStyleItemProvider.dispose();
		if (gridItemContainerItemProvider != null)
			gridItemContainerItemProvider.dispose();
		if (searchWidgetItemProvider != null)
			searchWidgetItemProvider.dispose();
		if (searchEventItemProvider != null)
			searchEventItemProvider.dispose();
		if (searchStyleItemProvider != null)
			searchStyleItemProvider.dispose();
		if (blankWidgetItemProvider != null)
			blankWidgetItemProvider.dispose();
		if (blankStyleItemProvider != null)
			blankStyleItemProvider.dispose();
		if (progressWidgetItemProvider != null)
			progressWidgetItemProvider.dispose();
		if (progressStyleItemProvider != null)
			progressStyleItemProvider.dispose();
		if (progressEventItemProvider != null)
			progressEventItemProvider.dispose();
		if (lineContainerItemProvider != null)
			lineContainerItemProvider.dispose();
		if (lineEventItemProvider != null)
			lineEventItemProvider.dispose();
		if (lineStyleItemProvider != null)
			lineStyleItemProvider.dispose();
		if (workOperationItemProvider != null)
			workOperationItemProvider.dispose();
		if (gridItemStyleItemProvider != null)
			gridItemStyleItemProvider.dispose();
		if (gridItemEventItemProvider != null)
			gridItemEventItemProvider.dispose();
	}

}
